INSERT INTO AUTHOR (ID, NAME, SURNAME) VALUES (1, 'Stephen', 'King');
INSERT INTO AUTHOR (ID, NAME, SURNAME) VALUES (2, 'Arturo', 'Perez-Reverte');
INSERT INTO PUBLISHER (ID, NAME) VALUES (1, 'Viking Press');
INSERT INTO PUBLISHER (ID, NAME) VALUES (2, 'Alfaguara');
INSERT INTO BOOK (ID, TITLE, YEAR, AUTHOR_ID, PUBLISHER_ID) VALUES (1, 'Cujo', 1981, 1, 1);
INSERT INTO BOOK (ID, TITLE, YEAR, AUTHOR_ID, PUBLISHER_ID) VALUES (2, 'I.T', 1986, 1, 1);
INSERT INTO BOOK (ID, TITLE, YEAR, AUTHOR_ID, PUBLISHER_ID) VALUES (3, 'La Reina del Sur', 2002, 2, 2);
INSERT INTO BOOK (ID, TITLE, YEAR, AUTHOR_ID, PUBLISHER_ID) VALUES (4, 'El club Dumas', 1993, 2, 2);